# hw_drc.yml
name: DRC

on:
  pull_request:
    branches: [main]
    paths: ['hardware/**']

jobs:
  DRC:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad9_auto:latest
    permissions:
      contents: write # Needed for committing checks back to the repo
    steps:
      - uses: actions/checkout@v6
      - name: Run DRC
        working-directory: hardware/pcb_1
        run: kibot -i -s erc
      - uses: actions/upload-artifact@v7
        with:
          name: DRC_Output
          path: hardware/pcb_1/fabrication/checks/DRC