# hw_drc.yaml
name: DRC

on:
  pull_request:
    branches: [main]
    paths: ['hardware/**']

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.find_boards.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6
      - name: Find KiCad projects
        id: find_boards
        run: |
          FOLDERS=$(find hardware -maxdepth 2 -name '*.kibot.yaml' | xargs -I{} dirname {} | sort | jq -R -s -c 'split("\n")[:-1]')
          echo "matrix={\"board\":$FOLDERS}" >> $GITHUB_OUTPUT

  DRC:
    needs: discover
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad9_auto:latest
    strategy:
      matrix: ${{ fromJson(needs.discover.outputs.matrix) }}
      fail-fast: false
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - name: Run DRC
        working-directory: ${{ matrix.board }}
        run: kibot -i -s erc
      - name: Upload DRC results
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: DRC_Output_${{ matrix.board }}
          path: ${{ matrix.board }}/fabrication/checks/DRC