# hw_erc.yaml
name: ERC

on:
  pull_request:
    branches: [main]
    paths: ['hardware/**']

jobs:
  ERC:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad9_auto:latest
    permissions:
      contents: write # Needed for committing checks back to the repo
    steps:
      - uses: actions/checkout@v6
      - name: Run ERC
        working-directory: hardware/pcb_1
        run: kibot -i -s drc
      - uses: actions/upload-artifact@v7
        with:
          name: ERC_Output
          path: hardware/pcb_1/fabrication/checks/ERC
